apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.5.2
      chart: grafana
      helm:
        valueFiles:
          - $values/values/grafana-overrides.yaml
    - repoURL: https://github.com/pbmoses/grafana-stack-argo.git
      targetRevision: HEAD 
      ref: values
  project: default
