apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-enterprise
  namespace: argocd
spec:
  destination:
    namespace: grafana-prod
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.5.2
      chart: grafana
      helm:
        valueFiles:
          - $values/values/grafana-viz-overrides.yaml
    - repoURL: https://github.com/pbmoses/agi-stack-argo.git
      targetRevision: HEAD 
      ref: values
  project: default
