apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.min.io/
      targetRevision: 5.3.0
      chart: minio
      helm:
        valueFiles:
          - $values/values/minio-overrides.yaml
    - repoURL: https://github.com/pbmoses/grafana-stack-argo.git 
      targetRevision: HEAD 
      ref: values
  project: default
